### ISSUE TITLE
app not defined

### ISSUE THREAD

**Issue by 57ar7up** [0x00A/scratches#6]
app.on('window-all-closed', () => {
    ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (C:\Users\User\Downloads\scratches-master\index.js:14:5)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3

**Comment by 0x00A** [comment]
You are looking for this...
```
const { remote } = require('electron')
console.log(remote.app)
```

Attaching these events might not be a good use case for a sandbox, but im not sure what you're actually trying to accomplish. Hope this helps :)
